name: release-please
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install Mage
        if: ${{ steps.release.outputs.release_created }}
        run: go install github.com/magefile/mage@latest

      - name: Run full CI validation
        if: ${{ steps.release.outputs.release_created }}
        run: mage ci
